# Blog Application - Complete Kubernetes Deployment
# Apply with: kubectl apply -f k8s-all-in-one.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: blog-app
  labels:
    name: blog-app
    app: blog-application

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-app-config
  namespace: blog-app
  labels:
    app: blog-application
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
  namespace: blog-app
  labels:
    app: blog-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-application
  template:
    metadata:
      labels:
        app: blog-application
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: blog-app
        image: acrblogappsdk8s.azurecr.io/blog-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: blog-app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/posts
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/posts
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
  namespace: blog-app
  labels:
    app: blog-application
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: blog-application

---
apiVersion: v1
kind: Service
metadata:
  name: blog-app-nodeport
  namespace: blog-app
  labels:
    app: blog-application
    service-type: nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: blog-application
