apiVersion: v1
kind: Service
metadata:
  name: blog-app-loadbalancer
  namespace: blog-app
  labels:
    app: blog-application
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: blog-application
